name: Build Project
run-name: Building latest version of ${{ github.repository }}
on:
  pull_request:
    branches:
      - master
jobs:
  build_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
      - name: Install Prerequisites
        run: sudo apt-get install -y mm-common docbook-xsl
      - name: Build and Install sigc++
        run: |
          wget https://download.gnome.org/sources/libsigc++/3.4/libsigc++-3.4.0.tar.xz
          tar Jxvf libsigc++-3.4.0.tar.xz
          cd libsigc++-3.4.0/
          ./autogen.sh --prefix=/usr/local
          make
          sudo make install
      - name: Configure cmake
        run: cmake -B build src
      - name: Compile project
        run: cmake --build build

