name: Build Project
run-name: Building latest version of ${{ github.repository }}
on:
  pull_request:
    branches:
      - master
jobs:
  build_project:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get -y install libgtkmm-4.0-dev
          sudo apt-get -y install cppcheck
      - name: Configure cmake
        run: cmake -B build src -DRUN_CPPCHECK=ON
      - name: Compile project
        run: cmake --build build

