name: Build Project (clang)
run-name: Building latest version of ${{ github.repository }} with Clang and Clang-Tidy
on:
  pull_request:
    branches:
      - master
jobs:
  build_project:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get -y install clang-tidy
      - name: Configure cmake
        run: cmake -B build src -DRUN_CLANG_TIDY=ON -DCMAKE_CXX_COMPILER=clang
      - name: Compile project
        run: cmake --build build -j

