name: CPPCheck
run-name: Running cppcheck for ${{ github.repository }}
on:
  pull_request:
    branches:
      - master
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
      - name: Install Prerequisites
        run: sudo apt-get install cppcheck
      - name: Run cppcheck
        run: cppcheck --enable=all --error-exitcode=1 --suppressions-list=cppcheck_suppression_list src
